### PR TITLE
Making assignments class/model

### PR DESCRIPTION
**Pull request by ignition-ctrl**
A cool project, I'd like to help. I added an option to filter the assignments titles so that users (if there are any more) can have them in a list. I have a lot of time on my hands, I could help develop this if there are any more endpoints. If you have a list of any other endpoints, I could add methods for them.

### CODE REVIEW

**Comment by Wolfhound905** [comment]
Hello! I am so excited to see this. I would have never imagined anyone using this, let alone making a pull request to my project! I am just curious do you use OnCourse at your school 👀

**Comment by Wolfhound905** [comment]
Also, I am going to hold off on this commit for now because I would rather make another model for assignments and classes and stuff like that. If you want to make that that would be great.

**Comment by ignition-ctrl** [comment]
Hey, yeah, my high school uses oncourse and I spend a lot of time on the command-line, so I was wondering if anyone found the API for it and I found this. It's really nice work. I'd love to add to it and make more models. Just wondering if there are any more endpoints, or only the ones here. BTW, I was looking through the commit history and found your oncourse ID and password. I think you can remove that commit from the history in Github.
It's crazy, the open-source community really has stuff for everything.
Can I add you on discord?

**Comment by Wolfhound905** [comment]
Ya, you can add me on discord, I would like to talk about it more there! Wolfhound905#1234

(I may have accidentally leaked my password, it has been changed lol)

**Pull request closed without merging**
